controller_list:
  - name: fake_arm_controller
    joints:
      - joint4
      - joint7
      - joint10
      - joint15
      - joint18
  - name: fake_hand_controller
    joints:
      - joint20
      - joint21