test_robot:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - joint4
      - joint7
      - joint10
      - joint15
      - joint18
      - joint20
      - joint21
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []
  arm_position_controller:
    type: position_controllers/JointPositionController
    joints:
      - joint4
      - joint7
      - joint10
      - joint15
      - joint18
    gains:
      joint4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint7:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint10:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint15:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint18:
        p: 100
        d: 1
        i: 1
        i_clamp: 1